# Generated by Django 5.2.6 on 2025-09-22 13:54

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_salutation', models.CharField(max_length=128, verbose_name='Letter salutation')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='street',
            field=models.CharField(max_length=128, verbose_name='Street a. No.'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=128, verbose_name='Street a. No.')),
                ('zipcode', models.CharField(max_length=128, verbose_name='ZIP')),
                ('city', models.CharField(max_length=128, verbose_name='City')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('d', 'Diverse')], default='m', max_length=1, verbose_name='Gender')),
                ('letter_salutation', models.CharField(max_length=128, verbose_name='Letter salutation')),
                ('prefixed_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Prefixed title')),
                ('first_name', models.CharField(max_length=128, verbose_name='Firstname')),
                ('last_name', models.CharField(max_length=128, verbose_name='Lastname')),
                ('postfixed_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Postfixed title')),
                ('job_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Job title')),
                ('job', models.CharField(max_length=128, verbose_name='Job')),
                ('additional_info', tinymce.models.HTMLField(blank=True, verbose_name='Additional info')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.family', verbose_name='Family')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'abstract': False,
            },
        ),
    ]
