# Generated by Django 5.2.6 on 2025-10-01 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_family_alter_company_email_alter_company_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.company', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
