# Generated by Django 5.2.6 on 2025-10-09 13:58

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_client_created_at_company_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_instructor',
            field=models.BooleanField(default=False, verbose_name='Is instructor'),
        ),
        migrations.CreateModel(
            name='CourseDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='E-mail')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('short_description', tinymce.models.HTMLField(blank=True, verbose_name='Short description')),
                ('long_description', tinymce.models.HTMLField(blank=True, verbose_name='Long description')),
                ('units', models.IntegerField(verbose_name='Units')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_descriptions', to='core.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Course description',
                'verbose_name_plural': 'Course descriptions',
                'abstract': False,
            },
        ),
    ]
