# Generated by Django 5.2.6 on 2025-10-13 14:13

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_client_is_instructor_coursedescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('title_extension', models.CharField(blank=True, max_length=128, null=True, verbose_name='Title extension')),
                ('additional_description', tinymce.models.HTMLField(blank=True, verbose_name='Additional description')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.coursedescription', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Begin')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course unit',
                'verbose_name_plural': 'Course units',
                'abstract': False,
            },
        ),
    ]
