# Generated by Django 5.2.6 on 2025-10-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_client_created_at_alter_company_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(related_name='given_courses', to='core.client', verbose_name='Instructors'),
        ),
    ]
