# Generated by Django 5.2.6 on 2025-10-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedescription',
            name='repeat_interval',
            field=models.IntegerField(default=7, verbose_name='Repeat interval'),
        ),
    ]
