# Generated by Django 5.2.6 on 2025-10-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_coursedescription_repeat_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='actual_costs',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Standard costs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursedescription',
            name='standard_costs',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Standard costs'),
            preserve_default=False,
        ),
    ]
