# Generated by Django 5.2.6 on 2025-10-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_course_actual_costs_coursedescription_standard_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='actual_costs',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Actual costs'),
        ),
    ]
