# Generated by Django 5.2.6 on 2025-10-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_course_actual_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Currency'),
        ),
    ]
