# Generated by Django 5.2.6 on 2025-10-27 15:37

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_company_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(verbose_name='Enrolled at')),
                ('paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Paid')),
                ('comments', tinymce.models.HTMLField(blank=True, verbose_name='Comments')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Client')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course Attendance',
                'verbose_name_plural': 'Course Attendances',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='attendees',
            field=models.ManyToManyField(related_name='attended_courses', through='core.CourseAttendance', to='core.client', verbose_name='Attendees'),
        ),
    ]
